function newpoint = icart2img(image_coord, imgcent_coordinate, XYZres)

newpoint = [((image_coord(2) - imgcent_coordinate(2))*XYZres(1));...
	     -((image_coord(1) - imgcent_coordinate(1))*XYZres(2));...
	     -((image_coord(3) - imgcent_coordinate(3))*XYZres(3))];
